defaults: &defaults
  access_key_id: "AKIAJGNRUJYVROTIJG3Q"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "ljcsite"
test:
  <<: *defaults
  bucket: "ljcsite"
production:
  access_key_id: <%= ENV['S3_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>
  bucket: "ljcsite"